version: 2.1

defaults:
  yarn_cache: &yarn_cache
    key: yarn_cache-v1-{{ checksum "yarn.lock" }}-{{ .Branch }}
  yarn_cache_keys: &yarn_cache_keys
    keys:
      - yarn_cache-v1-{{ checksum "yarn.lock" }}-{{ .Branch }}
      - yarn_cache-v1-{{ checksum "yarn.lock" }}
      - yarn_cache-v1

orbs:
  node: circleci/node@0.0.6

jobs:
  build_test_release:
    executor: node/node
    steps:
      - checkout
      - restore_cache:
          <<: *yarn_cache_keys
      - run:
          name: Build
          command: yarn
      - run:
          name: Test
          command: yarn start lint
      - run:
          name: Release
          command: yarn semantic-release || true
      - save_cache:
          <<: *yarn_cache
          paths:
            - ~/.cache/yarn

workflows:
  build_test_release:
    jobs:
      - build_test_release:
          context: org-global
